### ISSUE TITLE
Sorting results in incorrect bounds on path marks for SVG Renderer.

### ISSUE THREAD

**Issue by arvind** [vega/vega-scenegraph#15]
Reported by Roy I in the vega-js google group ([link](https://groups.google.com/d/msg/vega-js/18ebFiCANVQ/jAM0ENiqCQAJ)). 

1. Add `{"type": "sort", "by": ["-unemp.rate"]}` to the transforms of the `counties` dataset for [the choropleth example](http://vega.github.io/vega-editor/?spec=choropleth). 
2. Mouseover Hawaii (The Big Island). 
3. Bounds are calculated as `{x1: 670.1330560791714
x2: 678.0036158473883
y1: 304.77634754226824
y2: 308.55182487317563}`.
4. Without the sorting, bounds are `{x1: 330.2622391327014
x2: 352.19922920878605
y1: 470.32522201866715
y2: 495.52432103620583}`

The Canvas renderer correctly calculates the bounds both with and w/o sorting.

**Comment by jheer** [comment]
It looks like the sort is contributing to the data<->item mapping getting shuffled without proper bounds updates, hence the bounds on the items actually reference different geo-regions. I will work on fixing this. In the meantime, a quick fix is to set the padding to zero (`"padding": 0`), which prevents multiple invocations of the encoding pipeline such that the error doesn't surface for static visualizations.

**Comment by jheer** [comment]
Fixed in 47a6340, now released in vega-scenegraph 1.0.12. The fix should make the scenegraph correct, but _may_ incur a slight performance penalty in the common case of a stable sort order for mark items. More investigation is needed to see if there is any significant or noticeable performance difference. I did not note any obvious change on the current set of vega-editor examples.
