### ISSUE TITLE
jsdom-global conflict with headless renderer

### ISSUE THREAD

**Issue by alecf** [vega/vega-scenegraph#29]
in the 1.x branch, vega-scenegraph is using detection of document.createElement to determine if it is safe to create a `<canvas>` element rather than using node-canvas:

https://github.com/vega/vega-scenegraph/blob/v1.x/src/util/canvas.js#L6

When using react testing libraries like https://github.com/airbnb/enzyme, you need to have a global `jsdom` loaded: https://github.com/airbnb/enzyme/blob/master/docs/guides/jsdom.md and the `<canvas>` in jsdom is insufficient for the canvas renderer.

this means that no matter what, vega-scenegraph is going to try to use  jsdom's `<canvas>` element.

It would be nice if there were a better way to detect if `document.createElement()` should be used or not, or even better be able to force the use of `node-canvas`

**Comment by mathisonian** [comment]
This is related to vega/vega-wordcloud#1. I created a module called [safe-canvas](https://github.com/mathisonian/safe-canvas) that will change its export based on whether node (exports `node-canvas`) or a bundler like browserify/webpack (exports a `<canvas>` wrapper) is being used. 

Does that work for your use case?

**Comment by alecf** [comment]
yeah! that's a fantastic solution... much better to let node / npm decide than dynamically detect it at runtime. If the fix you put in CloudLayout.js were applied to canvas.js here, that would fix this problem.

**Comment by ericsoco** [comment]
Bump. This means that it's impossible to even run tests without `node-canvas` installed -- `jsdom`'s `<canvas>` is missing `getContext()` and so the [`canvas(true)` call in text.js](https://github.com/vega/vega-scenegraph/blob/master/src/util/text.js#L41) throws an error.

Note that `canvas(true)` call happens on module init -- it's triggered simply by `import Vega from 'vega'` anywhere in the code under test.

For now, I'm working around by conditionally requiring Vega only in the browser, instead of `import`ing.

Another fix might be to add a third conditional branch to [canvas.js](https://github.com/vega/vega-scenegraph/blob/master/src/util/canvas/canvas.js) -- if the instantiated `canvas` element exists, but there's no `getContext` function on it, return null. I modified the Vega source locally and this allows my test suite to run, but obviously I can't push that workaround to my repo.

**Comment by ericsoco** [comment]
Scratch that -- the repo I'm working in had a super-old version of `jsdom` -- they added support for `canvas.getContext` [in 8.0.0](https://github.com/tmpvar/jsdom/commit/24c6f9f56b3e8f8831950cbef71130a3ba95a4dc). 

Upgrading to latest `jsdom` eliminates the `getContext` error. Sorry for the noise!

**Comment by jheer** [comment]
Closing the issue as it appears that newer versions of JSDOM address this issue. If not, please feel free to re-open.
