### ISSUE TITLE
How can I specify where a line or area is defined?

### ISSUE THREAD

**Issue by besquared** [vega/vega-scenegraph#35]
In d3 there is a d3.defined function that allows things like discontinuous line segments. I've noticed that this exists in scenegraph in some way but it's not documented in vega and I'm not sure how it's intended to be used.

**Comment by jheer** [comment]
The key bit in vega-scenegraph is [/src/path/shapes.js#L23](https://github.com/vega/vega-scenegraph/blob/master/src/path/shapes.js#L23). This line tests the scenegraph item's `defined` property: if it is `false` we treat the data point as undefined, otherwise we treat it as defined.

To access this functionality from Vega, you can simply add a `"defined"` visual encoding property, which must evaluate to `false` if you want the data point to be treated as undefined.
```json
{
  "type": "line",
  "encode": {
    "enter": {
       "x": {...},
       "y": {...},
       "defined": {...}
    }
  }
}
```
(Yes, you do need to have an actual data element indicating that the particular data point is undefined, but that is how D3 v4 works, and is necessary to distinguish from cases where we should blindly interpolate through a missing point.)

I'm closing this issue as hopefully it is now resolved; please respond back if you run into any issues!
